name: build & test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Expo GitHub Action
      uses: expo/expo-github-action@v5
      with:
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
        expo-cache: true
    - run: echo '${{ secrets.APP_JSON }}' > app.json
    - run: npm ci

    - name: codechecks
      run: npx codechecks
      env:
        CC_SECRET: ${{ secrets.CC_SECRET }}

    - run: npm run test

    - run: expo doctor

    - name: deploy
      if: github.ref != 'refs/heads/master'
      run: |
          github_branch="${{ github.ref }}"
          github_branch=${github_branch//refs\/heads\//}
          expo publish --release-channel=dev.${github_branch//\//-}
  android-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: echo '${{ secrets.APP_JSON }}' > app.json
      - run: npm ci
      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12
          java-package: jdk
          architecture: x64
      - name: install appium dependencies (which must be installed globally)
        run:
          - npm i -g opencv4nodejs mjpeg-consumer
          - apt install ffmpeg
      - name: check if Appium is happy
        run: npx appium-doctor --android



