name: PR
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Expo GitHub Action
      uses: expo/expo-github-action@4.1.0
      with:
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
    - run: echo '${{ secrets.APP_JSON }}' > app.json
    - run: npm ci
  run-typecov:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
  run-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: npm run test
  run-expo-doctor:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: expo doctor
  run-expo-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: |
          github_branch="${{ github.head_ref }}"
          expo publish --release-channel=dev.${github_branch//\//-}
      
        
